name: Publish Types
on:
  push:
    branches:
      - main
    paths:
      - types/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        working-directory: ./types
        run: npx jsr publish